# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getZ <- function(pmat) {
    .Call('_NetMix_getZ', PACKAGE = 'NetMix', pmat)
}

approxBdyad <- function(y, node_id, pi_mat, directed) {
    .Call('_NetMix_approxBdyad', PACKAGE = 'NetMix', y, node_id, pi_mat, directed)
}

approxB <- function(y, pi_mat, directed) {
    .Call('_NetMix_approxB', PACKAGE = 'NetMix', y, pi_mat, directed)
}

mmsbm_fit <- function(z_t, x_t, y, time_id_dyad, time_id_node, nodes_per_period, node_id_dyad, mu_b, var_b, phi_init, kappa_init_t, b_init_t, beta_init, gamma_init, control) {
    .Call('_NetMix_mmsbm_fit', PACKAGE = 'NetMix', z_t, x_t, y, time_id_dyad, time_id_node, nodes_per_period, node_id_dyad, mu_b, var_b, phi_init, kappa_init_t, b_init_t, beta_init, gamma_init, control)
}

