# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approxB <- function(y, d_id, pi_mat) {
    .Call('_NetMix_approxB', PACKAGE = 'NetMix', y, d_id, pi_mat)
}

.getZ <- function(pmat) {
    .Call('_NetMix_getZ', PACKAGE = 'NetMix', pmat)
}

mmsbm_fit <- function(z_t, x_t, y, time_id_dyad, time_id_node, nodes_per_period, node_id_dyad, mu_b, var_b, phi_init, kappa_init_t, b_init_t, beta_init, gamma_init, control) {
    .Call('_NetMix_mmsbm_fit', PACKAGE = 'NetMix', z_t, x_t, y, time_id_dyad, time_id_node, nodes_per_period, node_id_dyad, mu_b, var_b, phi_init, kappa_init_t, b_init_t, beta_init, gamma_init, control)
}

